### ISSUE TITLE
give me acccess

### ISSUE THREAD

**Issue by master7720** [KillAura7170/Incoming#8]

**Comment by Wolfsurge** [comment]
do not give him access

**Comment by master7720** [comment]
skidder

**Comment by master7720** [comment]
> > skidder
> 
> :troll: not anymore

Cap

**Comment by master7720** [comment]
> do not give him access

ha got access

**Comment by Wolfsurge** [comment]
> > do not give him access
> 
> ha got access

Lmao

**Comment by master7720** [comment]
hey babe!

**Comment by Wolfsurge** [comment]
> hey babe!

heyyyy

**Comment by master7720** [comment]
> > hey babe!
> 
> heyyyy

you should rewrite momentum

**Comment by Wolfsurge** [comment]
> > > hey babe!
> > 
> > heyyyy
> 
> you should rewrite momentum 

nah I cba

**Comment by master7720** [comment]
> > > > hey babe!
> > > 
> > > 
> > > heyyyy
> > 
> > 
> > you should rewrite momentum
> 
> nah I cba

kk
